import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "@/components/header";
import "./globals.css";
import LastWatched from "@/components/last-watched";
import { Toaster } from "sonner";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} dark`}>
        <Header />
        <Toaster />

        <div className="pt-16">{children}</div>

        <LastWatched />
      </body>
    </html>
  );
}
